---
- name: Deploy PostgreSQL for BPMSoft
  hosts: postgresql_servers
  become: yes
  gather_facts: yes
  
  # Automatically switch to SSH key if available
  vars:
    ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
    
  pre_tasks:
    - name: Set PostgreSQL paths based on OS
      set_fact:
        postgresql_data_dir: "{{ '/var/lib/postgresql/16/main' if ansible_os_family == 'Debian' else '/var/lib/pgsql/16/data' }}"
        postgresql_config_dir: "{{ '/etc/postgresql/16/main' if ansible_os_family == 'Debian' else '/var/lib/pgsql/16/data' }}"
        postgresql_service_name: "{{ 'postgresql' if ansible_os_family == 'Debian' else 'postgresql-' + postgresql_version }}"
    
    - name: Update package cache (Debian)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install required packages (Debian)
      package:
        name:
          - wget
          - ca-certificates
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install required packages (RHEL)
      package:
        name:
          - wget
          - ca-certificates
          - gnupg2
          - yum-utils
        state: present
      when: ansible_os_family in ["RedHat", "RED"]

  roles:
    - role: postgresql_install
      tags: [install, postgresql]
    
    - role: postgresql_configure
      tags: [configure, postgresql]
    
    - role: postgresql_setup
      tags: [setup, postgresql]
    
    - role: postgresql_data
      tags: [data, postgresql]

  post_tasks:
    - name: Verify PostgreSQL is running
      systemd:
        name: "{{ postgresql_service_name }}"
        state: started
        enabled: yes
