---
collections:
  - name: community.postgresql
    version: ">=3.0.0"
  - name: community.general
    version: ">=5.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.crypto
    version: ">=2.0.0"

roles:
  - name: geerlingguy.postgresql
    version: ">=4.0.0"
