---
# Create SystemD service for BPMSoft

- name: Create SystemD service file
  template:
    src: dotnet-bpmsoft.service.j2
    dest: "/etc/systemd/system/{{ bpmsoft_service_name }}.service"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable BPMSoft service (without starting)
  systemd:
    name: "{{ bpmsoft_service_name }}"
    enabled: yes
    daemon_reload: yes

- name: Display service info
  debug:
    msg: "BPMSoft service created and enabled. Start manually after configuration."
