---
all:
  children:
    bpmsoft_servers:
      hosts:
        # Alventa-dev
        bpmsoft-alventa-dev:
          ansible_host: 192.168.154.12
          ansible_user: RightexAdmin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        
        # Alventa-preprod
        bpmsoft-alventa-preprod:
          ansible_host: 192.168.154.32
          ansible_user: RightexAdmin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        
        # Alventa-prod
        bpmsoft-alventa-prod:
          ansible_host: 192.168.154.17
          ansible_user: RightexAdmin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
      vars:
        ansible_python_interpreter: /usr/bin/python3
        bpmsoft_user: "dotnetuser"
        bpmsoft_home_dir: "/data/bpmsoft"
