---
- name: Deploy BPMSoft Environment
  hosts: bpmsoft_servers
  become: yes
  gather_facts: yes
  
  # Automatically switch to SSH key if available
  vars:
    ansible_ssh_private_key_file: "{{ ssh_private_key | default('~/.ssh/id_rsa') }}"
  
  pre_tasks:
    - name: Set OS-specific variables
      set_fact:
        package_manager: "{{ 'apt' if ansible_os_family == 'Debian' else 'yum' }}"
        dotnet_packages:
          - "{{ 'dotnet-sdk-8.0' if ansible_os_family == 'Debian' else 'dotnet-sdk-8.0' }}"
          - "{{ 'dotnet-runtime-8.0' if ansible_os_family == 'Debian' else 'dotnet-runtime-8.0' }}"
  
  roles:
    - role: bpmsoft_dotnet
      tags: [dotnet, install]
    
    - role: bpmsoft_user
      tags: [user, setup]
    
    - role: bpmsoft_directories
      tags: [directories, setup]
    
    - role: bpmsoft_systemd
      tags: [systemd, service]
  
  post_tasks:
    - name: Verify BPMSoft environment
      debug:
        msg: "BPMSoft environment is ready on {{ inventory_hostname }}"
